# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_deesigns.ui/aes_dec_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowDecFile(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QPushButton {\n"
" background: #01040f;\n"
"    padding: 20px 30px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    color: #fff;\n"
"    text-align: center;\n"
"    border-radius: 20px;\n"
"    margin: 4px 2px;\n"
"    border: 1px solid #0bd42c;\n"
"\n"
"}\n"
"QMainWindow {\n"
" background: #000;\n"
"\n"
"}\n"
"QLabel {\n"
" background: #000;\n"
"color: #fff;\n"
"font-size: 13px;\n"
" font-weight: bold;\n"
"\n"
"}\n"
"\n"
"QSpinBox {\n"
" background: #1b4725;\n"
" border-radius: 7px;\n"
" font-weight: bold;\n"
" font-size: 23px;\n"
"\n"
"}\n"
"\n"
"QRadioButton {\n"
" background: #000;\n"
" border-radius: 7px;\n"
" font-weight: bold;\n"
" font-size: 15px;\n"
"color: #1b4725;\n"
"}\n"
"\n"
"QTextEdit {\n"
" background: #6e9c78;\n"
" border-radius: 7px;\n"
" font-weight: bold;\n"
" font-size: 13px;\n"
"color: #fff;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(520, 250, 221, 81))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 510, 131, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(570, 510, 171, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 30, 161, 71))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
" background: #01040f;\n"
"   \n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    color: #fff;\n"
"\n"
"    border-radius: 20px;\n"
"\n"
"    border: 1px solid #0bd42c;\n"
"\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 260, 141, 61))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 121, 61))
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(190, 250, 161, 71))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
" background: #01040f;\n"
"   \n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    color: #fff;\n"
"\n"
"    border-radius: 20px;\n"
"\n"
"    border: 1px solid #0bd42c;\n"
"\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 420, 171, 71))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Расшифровать"))
        self.pushButton_2.setText(_translate("MainWindow", "Назад"))
        self.pushButton_3.setText(_translate("MainWindow", "Главное меню"))
        self.pushButton_4.setText(_translate("MainWindow", "Выбрать файл!"))
        self.label.setText(_translate("MainWindow", "Выберите файл\n"
"с ключем:"))
        self.label_3.setText(_translate("MainWindow", "Нажмите чтобы\n"
"выбрать файл:"))
        self.pushButton_5.setText(_translate("MainWindow", "Выбрать файл!"))
        self.label_4.setText(_translate("MainWindow", "Расшифрованный файл\n"
"находится в одном\n"
"каталоге с программой"))
