# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_designs/algoritm_encript.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowAlgoritmEncript(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QPushButton {\n"
" background: #01040f;\n"
"    padding: 20px 30px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    color: #fff;\n"
"    text-align: center;\n"
"    border-radius: 20px;\n"
"    margin: 4px 2px;\n"
"    border: 1px solid #0bd42c;\n"
"\n"
"}\n"
"\n"
"QMainWindow {\n"
"background: #000;\n"
"}\n"
"QLabel {\n"
" background: #000;\n"
"color: #064f15;\n"
"font-size: 40px;\n"
" font-weight: bold;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 120, 521, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Button_AES = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Button_AES.setObjectName("Button_AES")
        self.gridLayout.addWidget(self.Button_AES, 2, 0, 1, 1)
        self.Button_RSA = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Button_RSA.setObjectName("Button_RSA")
        self.gridLayout.addWidget(self.Button_RSA, 0, 0, 1, 1)
        self.Button_Cezar = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Button_Cezar.setObjectName("Button_Cezar")
        self.gridLayout.addWidget(self.Button_Cezar, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 731, 51))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 510, 121, 71))
        self.pushButton.setStyleSheet("QPushButton {\n"
"background: #01040f;\n"
"font-size: 15px;\n"
"font-weight: bold;\n"
"color: #fff;\n"
"    border-radius: 10px;\n"
"    border: 1px solid #0bd42c;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_AES.setText(_translate("MainWindow", "AES"))
        self.Button_RSA.setText(_translate("MainWindow", "RSA"))
        self.Button_Cezar.setText(_translate("MainWindow", "Шифр Цезаря"))
        self.label.setText(_translate("MainWindow", "Выбирете алгоритм шифрования"))
        self.pushButton.setText(_translate("MainWindow", "Назад"))
